version: '3.4'

services:
  tanslatorspacegrpcservice:
    image: tanslatorspacegrpcservice
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "50051:50051"